### ISSUE TITLE
まとめ機能の時刻がJST表示じゃない

### ISSUE THREAD

**Issue by nidosina** [raito417/mistodon-sitabot#5]
こんな感じで修正（.replace(tzinfo=JST)も必要？）
format_times(time)とは別に一括で日本時間にする関数がほしい

`first = sitakoto_dict[0] + datetime.timedelta(hours=9)`
https://github.com/raito417/mistodon-sitabot/blob/master/sita.py#L173

`first, last = sitakoto_dict[0] + datetime.timedelta(hours=9), sitakoto_dict[-1] + datetime.timedelta(hours=9)`
https://github.com/raito417/mistodon-sitabot/blob/master/sita.py#L182

**Comment by raito417** [comment]
提案ありがとう
まとめの時刻に関しては修正しました
確かに一括で日本時間にする関数はほしいので実装予定です

**Comment by raito417** [comment]
https://github.com/raito417/mistodon-sitabot/commit/31f216daf55e97cefa8d5cab8568f695d221db38#diff-e4ce80b069b43b2dd2b7a375ab3a7b3eb4aa63c4abb274a8a919bab8ccd698b6
関数to_jst()を追加してサーバーの時間に9時間足してタイムゾーンをJSTにするようにした
環境が変わってサーバーの時間が違うと時刻がずれる問題に関しては棚上げし問題が起こってから対処
